# Numpy (numerical Phython) (인덱싱은 접근 시 무조건 꺽쇠 [])

### 1. 넘파이 설치 확인

In [3]:
import numpy as np
print(np.__version__)

2.0.1


 ### 2. 넘파이 배열(array) 생성과 속성 확인


In [6]:
a1 = np.array([1,2,3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
a2 = np.array((1,2,3,))
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [9]:
a3 = np.array([[1,2,3],[4,5,6]])
print(a3, type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> int64 2 (2, 3) 6


# (< 의 의미는 유니코드로 21바이트 계산) 

In [11]:
a6 = np.array([1,4,5,'8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

<class 'numpy.ndarray'> <U21 1 (4,) 4


배열 차원이 안 만들어 지는 경우

In [19]:
test_list = [[1,2,3,4], [1,2,3]]
np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3.넘파이 인덱싱 (indexing)

In [22]:
d3 = np.arange(12).reshape(2,2,3)
print(d3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [24]:
d3[0] = 50
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [28]:
d3[1,0] = 30
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[30 30 30]
  [ 9 10 11]]]


### 4.넘파이 슬라이싱

In [3]:
import numpy as np
d = np.array([1,2,3,4,5,6,7,8,9,])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [11]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2[0])
print(d2[0,:])
print(d2[:,:-1])
print(d2[::2,::2])

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [13]:
d3 = np.arange(12).reshape(2,2,3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [14]:
#슬라이싱된 요소 값을 한꺼번에 변경
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2)
print(d2[::2,::3])
d2[::2,::3] = 30
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]


In [32]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2)
d2[1:,1:] = -1
print(d2) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6 -1 -1 -1 -1]]


In [12]:
# 전체 요소값을 한꺼번에 변경
d2[:,:] = 1 
print(d2)

[[1 1 1 1 1]
 [1 1 1 1 1]]


### 5.불린형(Boolean) 인덱스

In [15]:
#조건에 맞는 결과만 배열에 포함 
# 대괗호는 조건식 뿐만 아니라 넘파이에서 제공하는 함수 사용 가능
data = np.array([4,6,7,3,2,0])
print(data[data > 3])

[4 6 7]


In [17]:
print(data > 3)
cond = [False, True, True, False, False, True]
data[cond]

[ True  True  True False False False]


array([6, 7, 0])

In [20]:
# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 3) & (data < 6)])
# 찍수만 출력
print(data[data % 2 == 0])
# 평균보다 작은 값만 추출
print(data[data < data.mean( )]) #.mean 이 평균

[4]
[4 6 2 0]
[3 2 0]


In [38]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data > 3) # 전체 값에 대한 조건 답을 모두 표현
print(data[data > 3]) #내가 원하는 데이터만 인덱싱 되는 조건
print(data[(data > 3) & (data < 6)]) #2보다 크고 6보다 작은 요소만 추출
print(data[data % 2==0])#짝수만 출력
print(data[data <data.mean( )]) #평균보다 작은 값만 출력

[ True  True  True False False False]
[4 6 7]
[4]
[4 6 2 0]
[3 2 0]


### 6.펜시 인덱싱 (fancy indexing)
    배열 명 [list of index]

In [24]:
# 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함
# 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스 범위 내
# 대상이 되는 배열과 인덱스 배열의 구조(shape)가 같을 필요는 없음
f = np.array([4,6,7,3,2])
indexes = np.array([1,2,0,2,2,2])
f[indexes]

array([6, 7, 4, 7, 7, 7])

In [25]:
f2 = np.array([[1,4], [9,16]])
x = np.array([0,1,1,1,0,0])
y = np.array([0,0,0,1,1,1])
f2[x,y]

array([ 1,  9,  9, 16,  4,  4])

### 7. 넘파이 배열의 정렬(Sort)

In [29]:
#기본정렬 sort 함수
#sorted_narray = np.sort(ndarray):정렬된 배열을 반환
#ndarray.sort(): in-place sort
#오름차순 정렬만 지원
#내림차순 정렬을 위란 slicing [::-1] 활용
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

numbers.sort()
print(numbers)

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [36]:
#2차원 배열읠 정렬
#매개변수 axis를 사용 하여 행 또는 열 기준으로 출력
 # -. axis = 0:행 방향으로 정렬
 # -. axis = 1:열 방향으로 정렬

numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_numbers = np.sort(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

numbers.sort()
print(numbers)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [41]:
arr2d = np.array([[5,6,7,8], [4,3,2,1], [10,9,12,11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d, axis = 1))
print(np.sort(arr2d, axis = 0))

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [43]:
# 인덱스 반환 정렬: argsort 함수 
# sorted_index_list = np.argsort(ndarray) (정렬된 값의 index를 반환)
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

[5 0 4 6 7 8 3 1 2]


In [42]:
#[연습문제] 성적 순 으로 정렬 (내림차순)
names = np.array(['john', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

scores_sorted_index = np.argsort(scores)[::-1]
print(scores_sorted_index)
print(names[scores_sorted_index])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'john']


### 8.넘파이 배열의 사칙연산

In [45]:
#넘파이는 파이썬과 동일하게 배열 간에 사칙연산 지원
# 행렬과 행렬, 백터와 백터 간 사칙연산 가능

# 같은 배열의 구조 일 때 요소별 연산 (element-wise operation)
# 요소별 연산: 두 배열의 구조가 동일 한 경우 같은 인덱스 요소들 끼리 연산
x = np.arange(1,7).reshape(2,3)
x + x 
x + 2
y = np.array([10, 20, 30])
x + y

array([[11, 22, 33],
       [14, 25, 36]])

In [52]:
import numpy as np

d1 = np.array([[1,2,3], [4,5,6]])

print(d1)
# 넘파이 배열의 각 함수 들 축을 따라 구하는 함수
print(d1.sum(axis = None))
print(d1.mean(axis = None))
print(d1.max(axis = None))
print(d1.min(axis = None))

[[1 2 3]
 [4 5 6]]
21
3.5
6
1


In [56]:
#넘파이 배열 데이터 중 max, min의 값이 있는 index 반환
print(d1.argmax(axis = None))
print(d1.argmin(axis = None))


5
0


In [55]:
# 배열 내부의 모든 값이 참일 때는 True, 하나라도 참이 아닐 경우에는 False를 반환
# and 조건을 전체 요소에 적용
print(d1.all(axis = None))
print(np.all(d1,axis = None))



True
True


In [58]:
print(d1.any(axis = None))
print(np.any(d1,axis = None))


True
True


In [60]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1,2, np.nan,4])
print(np.any(np.isnan(data)))

# 2. 두 배열이 완전히 동일한지 확인
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.all(arr1 == arr2)) #True (요소별 비교 후 전체 확인)

True
True
